import { User } from "../User/User.ts";

export const MockUsers = [
  new User({
    id: 1,
    name: "Justin",
    nickname: "one",
    password: "1",
    wins: 20,
    loses: 1,
    rank: 1,
    history: [
      {
        matchDate: new Date(),
        player1: "one",
        player2: "two",
        matchId: 1,
        result: "won",
      },
      {
        matchDate: new Date(),
        player1: "one",
        player2: "three",
        matchId: 1,
        result: "loss",
      },
    ],
  }),
  new User({
    id: 2,
    name: "BJ",
    nickname: "two",
    password: "1",
    wins: 19,
    loses: 2,
    rank: 2,
    history: [
      {
        matchDate: new Date(),
        player1: "two",
        player2: "three",
        matchId: 1,
        result: "won",
      },
      {
        matchDate: new Date(),
        player1: "two",
        player2: "four",
        matchId: 1,
        result: "loss",
      },
    ],
  }),
  new User({
    id: 3,
    name: "Alan",
    nickname: "three",
    password: "1",
    wins: 18,
    loses: 3,
    rank: 3,
    history: [
      {
        matchDate: new Date(),
        player1: "one",
        player2: "two",
        matchId: 1,
        result: "won",
      },
      {
        matchDate: new Date(),
        player1: "one",
        player2: "three",
        matchId: 1,
        result: "loss",
      },
    ],
  }),
  new User({
    id: 4,
    name: "Andrew",
    nickname: "four",
    password: "1",
    wins: 17,
    loses: 4,
    rank: 4,
    history: [
      {
        matchDate: new Date(),
        player1: "one",
        player2: "two",
        matchId: 1,
        result: "won",
      },
      {
        matchDate: new Date(),
        player1: "one",
        player2: "three",
        matchId: 1,
        result: "loss",
      },
    ],
  }),
  new User({
    id: 5,
    name: "Tim X",
    nickname: "five",
    password: "1",
    wins: 16,
    loses: 5,
    rank: 5,
    history: [
      {
        matchDate: new Date(),
        player1: "one",
        player2: "two",
        matchId: 1,
        result: "won",
      },
      {
        matchDate: new Date(),
        player1: "one",
        player2: "three",
        matchId: 1,
        result: "loss",
      },
    ],
  }),
  new User({
    id: 6,
    name: "Tim O",
    nickname: "six",
    password: "1",
    wins: 15,
    loses: 6,
    rank: 6,
    history: [
      {
        matchDate: new Date(),
        player1: "one",
        player2: "two",
        matchId: 1,
        result: "won",
      },
      {
        matchDate: new Date(),
        player1: "one",
        player2: "three",
        matchId: 1,
        result: "loss",
      },
    ],
  }),
  new User({
    id: 7,
    name: "Aanand",
    nickname: "sev",
    password: "1",
    wins: 14,
    loses: 7,
    rank: 7,
    history: [
      {
        matchDate: new Date(),
        player1: "one",
        player2: "two",
        matchId: 1,
        result: "won",
      },
      {
        matchDate: new Date(),
        player1: "one",
        player2: "three",
        matchId: 1,
        result: "loss",
      },
    ],
  }),
  new User({
    id: 8,
    name: "Marcus",
    nickname: "eight",
    password: "1",
    wins: 13,
    loses: 8,
    rank: 8,
    history: [
      {
        matchDate: new Date(),
        player1: "one",
        player2: "two",
        matchId: 1,
        result: "won",
      },
      {
        matchDate: new Date(),
        player1: "one",
        player2: "three",
        matchId: 1,
        result: "loss",
      },
    ],
  }),
  new User({
    id: 9,
    name: "Seth",
    nickname: "nine",
    password: "1",
    wins: 12,
    loses: 9,
    rank: 9,
    history: [
      {
        matchDate: new Date(),
        player1: "one",
        player2: "two",
        matchId: 1,
        result: "won",
      },
      {
        matchDate: new Date(),
        player1: "one",
        player2: "three",
        matchId: 1,
        result: "loss",
      },
    ],
  }),
  new User({
    id: 10,
    name: "Ed",
    nickname: "ten",
    password: "1",
    wins: 11,
    loses: 10,
    rank: 10,
    history: [
      {
        matchDate: new Date(),
        player1: "one",
        player2: "two",
        matchId: 1,
        result: "won",
      },
      {
        matchDate: new Date(),
        player1: "one",
        player2: "three",
        matchId: 1,
        result: "loss",
      },
    ],
  }),
  new User({
    id: 11,
    name: "Jason",
    nickname: "el",
    password: "1",
    wins: 10,
    loses: 11,
    rank: 11,
    history: [
      {
        matchDate: new Date(),
        player1: "one",
        player2: "two",
        matchId: 1,
        result: "won",
      },
      {
        matchDate: new Date(),
        player1: "one",
        player2: "three",
        matchId: 1,
        result: "loss",
      },
    ],
  }),
  new User({
    id: 12,
    name: "Shelby",
    nickname: "twelve",
    password: "1",
    wins: 9,
    loses: 12,
    rank: 12,
    history: [
      {
        matchDate: new Date(),
        player1: "one",
        player2: "two",
        matchId: 1,
        result: "won",
      },
      {
        matchDate: new Date(),
        player1: "one",
        player2: "three",
        matchId: 1,
        result: "loss",
      },
    ],
  }),
];
